export const GUARDRAILS_CONFIG = {
  maxInputLength: 5000,
  maxChatMessageLength: 3000,
  maxTransactionTextLength: 1000,

  allowedTopicKeywords: [
    "transaction", "transaccion", "transacción", "gasto", "ingreso", "expense", "income",
    "budget", "presupuesto", "debt", "deuda", "loan", "préstamo", "prestamo",
    "payment", "pago", "balance", "saldo", "savings", "ahorro", "ahorros",
    "credit", "crédito", "credito", "card", "tarjeta", "money", "dinero", "plata",
    "salary", "salario", "sueldo", "nómina", "nomina", "wage",
    "bill", "factura", "cuenta", "recibo", "receipt",
    "invest", "inversión", "inversion", "interest", "interés", "interes", "apr",
    "mortgage", "hipoteca", "rent", "arriendo", "alquiler",
    "subscription", "suscripción", "suscripcion",
    "tax", "impuesto", "iva",
    "category", "categoría", "categoria",
    "report", "reporte", "informe", "análisis", "analisis", "analysis",
    "forecast", "pronóstico", "pronostico", "prediction", "predicción", "prediccion",
    "spending", "spend", "spent", "cost", "costo", "precio", "price",
    "transfer", "transferencia", "bank", "banco",
    "cop", "peso", "pesos", "dollar", "dólar", "dolar", "usd",
    "month", "mes", "weekly", "semanal", "daily", "diario", "annual", "anual",
    "buy", "compra", "comprar", "sell", "venta", "vender",
    "grocery", "groceries", "mercado", "supermercado",
    "food", "comida", "restaurant", "restaurante",
    "transport", "transporte", "uber", "gas", "gasolina",
    "utility", "utilities", "servicios", "agua", "luz", "electricity",
    "insurance", "seguro", "health", "salud",
    "education", "educación", "educacion",
    "entertainment", "entretenimiento",
    "shopping", "compras",
    "travel", "viaje",
    "payoff", "paydown", "avalanche", "snowball", "amortization", "amortización",
    "financial", "financiero", "finance", "finanzas",
    "csv", "import", "importar", "export", "exportar",
    "ayer", "hoy", "today", "yesterday",
    "cuánto", "cuanto", "cuántos", "cuantos", "how much", "how many",
    "delete", "eliminar", "borrar", "edit", "editar", "update", "actualizar",
    "add", "agregar", "añadir", "create", "crear",
    "show", "mostrar", "ver", "list", "listar",
    "help", "ayuda",
    "hello", "hola", "hi", "hey", "buenos días", "buenas",
  ],

  blockedTopicPatterns: [
    { pattern: /\b(hack|hacking|exploit|vulnerability|malware|virus|trojan|ransomware|phishing|ddos|dos attack)\b/i, topic: "cybersecurity attacks" },
    { pattern: /\b(bomb|weapon|gun|ammunition|explosive|terroris[mt])\b/i, topic: "weapons/violence" },
    { pattern: /\b(drug|cocaine|heroin|methamphetamine|narcotic|illegal substance)\b/i, topic: "illegal drugs" },
    { pattern: /\b(suicide|self.?harm|kill myself|end my life)\b/i, topic: "self-harm" },
    { pattern: /\b(porn|pornograph|explicit sexual|nude|naked)\b/i, topic: "adult content" },
    { pattern: /\b(how to (steal|rob|fraud|forge|counterfeit|launder))\b/i, topic: "illegal activities" },
    { pattern: /\b(money launder|launder money|wash money|lavar dinero)\b/i, topic: "money laundering" },
    { pattern: /\b(medical advice|diagnos[ei]|prescri[bp]|symptom|medication|disease|treatment plan)\b/i, topic: "medical advice" },
    { pattern: /\b(legal advice|sue |lawsuit|attorney|lawyer|litigat)\b/i, topic: "legal advice" },
    { pattern: /\b(write (a |an |my )?(essay|story|poem|novel|script|code|program))\b/i, topic: "content generation" },
    { pattern: /\b(who (is|was) the president|capital of|history of|geography)\b/i, topic: "general knowledge" },
    { pattern: /\b(recipe|cook|bake|ingredient|cuisine)\b/i, topic: "cooking" },
    { pattern: /\b(workout|exercise routine|gym program|diet plan|weight loss plan)\b/i, topic: "fitness" },
    { pattern: /\b(horoscope|zodiac|astrology|tarot|fortune tell)\b/i, topic: "astrology" },
    { pattern: /\b(election|political party|democrat|republican|liberal|conservative|vote for)\b/i, topic: "politics" },
    { pattern: /\b(religion|god|pray|church|mosque|temple|bible|quran|spiritual)\b/i, topic: "religion" },
  ],

  promptInjectionPatterns: [
    /ignore\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions?|prompts?|rules?|context)/i,
    /forget\s+(all\s+)?(previous|prior|your)\s+(instructions?|rules?|context|training)/i,
    /disregard\s+(all\s+)?(previous|prior|your)\s+(instructions?|rules?|guidelines)/i,
    /override\s+(all\s+)?(previous|your)\s+(instructions?|rules?|settings)/i,
    /you\s+are\s+now\s+(a|an|my)\s+(?!financial|finance|budget|debt|money)/i,
    /act\s+as\s+(a|an)\s+(?!financial|finance|budget|debt|money)/i,
    /pretend\s+(to\s+be|you\s*('re|are))\s+(?!a\s+(financial|finance))/i,
    /new\s+persona|new\s+identity|new\s+role|switch\s+mode/i,
    /\bsystem\s*prompt\b/i,
    /\bsystem\s*message\b/i,
    /\bsystem\s*instruction/i,
    /\[\s*system\s*\]/i,
    /\{\s*"role"\s*:\s*"system"/i,
    /^<\s*system\s*>/i,
    /<\|im_start\|>/i,
    /\bDAN\s*(mode)?\b/i,
    /\bdev(eloper)?\s*mode\b/i,
    /\bjailbreak\b/i,
    /do\s+anything\s+now/i,
    /\bunfiltered\s+mode\b/i,
    /\bno\s+(rules?|restrictions?|limits?|filter|guardrail)\b/i,
    /bypass\s+(security|safety|filter|restriction|guardrail|content\s+policy)/i,
    /reveal\s+(your|the|system)\s+(prompt|instructions?|rules?|training)/i,
    /show\s+me\s+(your|the)\s+(system|initial|original)\s+(prompt|instructions?|message)/i,
    /what\s+(are|were)\s+your\s+(initial|original|system)\s+(instructions?|prompt)/i,
    /repeat\s+(your|the)\s+(system|initial)\s+(prompt|message|instructions?)/i,
    /print\s+(your|the)\s+(system|initial)\s+(prompt|instructions?)/i,
  ],

  dataExfiltrationPatterns: [
    /\b(show|give|tell|list|display|reveal|dump)\b.*\b(all\s+users?|other\s+users?|every\s+user|other\s+(people|person)'?s?)\b/i,
    /\b(database|db)\s*(credentials?|password|connection\s*string|url|host|secret)/i,
    /\b(api|secret)\s*key/i,
    /\b(env|environment)\s*(var|variable)/i,
    /\b(access|auth)\s*token/i,
    /\bpassword\b/i,
    /\bsupabase\s*(url|key|secret|anon)/i,
    /\b(openai|gemini)\s*(api)?\s*key/i,
    /\bprocess\.env\b/i,
    /\b(select|insert|update|delete|drop|alter|truncate)\s+(from|into|table)/i,
    /\bunion\s+select\b/i,
    /;\s*(drop|delete|truncate|alter)\s/i,
  ],

  harmfulContentPatterns: [
    /\b(create|make|generate)\s+(fake|fraudulent|forged)\s+(transaction|receipt|invoice|document)/i,
    /\b(inflate|fake|falsify|fabricate)\s+(my\s+)?(balance|income|salary|revenue|earnings)/i,
    /\b(hide|conceal|obscure)\s+(income|transaction|money|earnings|revenue)\s+(from|against)/i,
    /\b(tax\s*(evasion|fraud)|evade\s+tax|avoid\s+paying\s+tax)/i,
    /\b(identity\s*theft|steal\s*(identity|identities))\b/i,
    /\b(credit\s*card\s*fraud|card\s*skimming|carding)\b/i,
  ],

  userFacingMessages: {
    prompt_injection: "I can't process that request. I'm designed to help only with personal finance tasks like tracking transactions, budgets, debts, and financial analysis.",
    jailbreak: "I'm FinFlow's financial assistant and I can only help with finance-related tasks. Please ask me about your transactions, budgets, debts, or financial reports.",
    off_topic: "That topic is outside my scope. I'm your personal finance assistant — I can help you with transactions, budgets, debts, reports, and financial advice. How can I help with your finances?",
    harmful_content: "I can't help with that request. I'm here to help you manage your finances responsibly and legally.",
    data_exfiltration: "I can only access your own financial data. I can't retrieve system credentials, other users' data, or internal configuration.",
    excessive_length: "Your message is too long. Please keep it under {maxLength} characters.",
    output_relevance: "I had trouble generating a relevant response. Could you rephrase your question about your finances?",
    sensitive_data_leak: "I detected potentially sensitive information in the response and filtered it out for your safety.",
  },
} as const
